GET http://localhost:5000/resource HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IlJvYmVydCBEYWhsYm9yZyIsImlhdCI6MTUxNjIzOTAyMiwic2NvcGVzIjoiZGVzaXJlZC1zY29wZSJ9.xXvOrjUL0Faf_FOZz6RHNsQFRYOhH8i62bGnSGf2jo4

<request>
    <name>sample</name>
    <time>Wed, 21 Oct 2015 18:27:50 GMT</time>
</request>